### PR TITLE
Added code of Version 0.19.0

### PR DESCRIPTION
**Pull request by slintes**
HCO wants to update to KubeVirt v0.19.0, but I didn't manage to convince `dep` to look at kubevirt's staging dir for the client-go code. So I want to copy the code of the v0.19.0 tag manually here for now. We need to automate this later on for sure.
Once this is merged, we need a v0.19.0 tag on it.

What I did:

- copied sources from staging
- copied go.mod from kubevirt root, set correct module name, removed kubevirt/client-go dependency
- run go mod tidy && go mod vendor

My fork is used in https://github.com/kubevirt/hyperconverged-cluster-operator/pull/177 for testing.

/cc @cynepco3hahue 
/cc @rmohr

### CODE REVIEW

**Comment by rmohr** [comment]
@slintes can you commit it without the vendor dependencies? They can't be directly consumed by other projects afaik.

**Comment by slintes** [comment]
@rmohr done

**Comment by slintes** [comment]
just for reference: this manual process will be replaced by https://github.com/kubevirt/kubevirt/pull/2510

**Comment by rmohr** [comment]
@slintes as discussed offline, can you directly push it to tag v0.19.0?

**Comment by slintes** [comment]
@rmohr done, thx

/close

**Pull request closed without merging**
